//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siemplify.Integrations.WebSense.SqlDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class summary_url
    {
        public long record_number { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<short> disposition_code { get; set; }
        public Nullable<int> protocol_id { get; set; }
        public Nullable<int> url_id { get; set; }
        public string url { get; set; }
        public Nullable<long> source_server_ip_int { get; set; }
        public Nullable<long> source_ip_int { get; set; }
        public Nullable<long> destination_ip_int { get; set; }
        public Nullable<int> port { get; set; }
        public Nullable<long> bytes_received { get; set; }
        public Nullable<long> bytes_sent { get; set; }
        public Nullable<int> hits { get; set; }
        public Nullable<int> browse_time { get; set; }
        public byte[] source_ip_bin { get; set; }
        public byte[] destination_ip_bin { get; set; }
    }
}
