//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siemplify.Integrations.WebSense.SqlDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_names
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_login_name { get; set; }
        public string user_full_name { get; set; }
        public string @namespace { get; set; }
        public string user_display_name { get; set; }
        public string catalog_server { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public string domain { get; set; }
        public int domain_id { get; set; }
    }
}
